# Generated by Django 2.0.9 on 2018-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20181224_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='tweets',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='tweets.HashTag'),
        ),
    ]
