# Generated by Django 2.0.9 on 2018-12-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20181224_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweets',
            new_name='hashtags',
        ),
    ]
