# Generated by Django 2.0.9 on 2018-12-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20181224_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(to='tweets.Tweet'),
        ),
    ]
